apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
        - name: food-app
          image: ndinevski/food-app:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
