apiVersion: v1
kind: Service
metadata:
  name: food-app-service
  labels:
    app: food-app
spec:
  selector:
    app: food-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
